import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
import Quickshell.Io

FocusScope {
    id: root
    anchors.fill: parent
    focus: true

    // Theme fallbacks for Omarchy
    QtObject {
        id: theme
        property color bg: (typeof qs !== 'undefined' && qs.Commons && qs.Commons.palette && qs.Commons.palette.window) ? qs.Commons.palette.window : "#1e1e2e"
        property color text: (typeof qs !== 'undefined' && qs.Commons && qs.Commons.palette && qs.Commons.palette.windowText) ? qs.Commons.palette.windowText : "#cdd6f4"
        property color accent: (typeof qs !== 'undefined' && qs.Commons && qs.Commons.palette && qs.Commons.palette.highlight) ? qs.Commons.palette.highlight : "#89b4fa"
        property color surface: (typeof qs !== 'undefined' && qs.Commons && qs.Commons.palette && qs.Commons.palette.button) ? qs.Commons.palette.button : "#313244"
        property string fontFamily: (typeof qs !== 'undefined' && qs.Commons && qs.Commons.fontFamily) ? qs.Commons.fontFamily : "sans-serif"
    }

    property bool isCapturing: false
    property string capturedMod: ""
    property string capturedKey: ""
    property var keybinds: []
    
    property string configPath: System.getenv("HOME") + "/.config/hypr/omarchy-keybinds.conf"

    // Read Config - now reads full Hyprland config
    Process {
        id: readProcess
        command: ["sh", "-c", `grep -E '^bind = ' ${configPath} 2>/dev/null || cat ${configPath}`]
        stdout: StdioCollector {
            onStreamFinished: parseConfig(text)
        }
        onRunningChanged: if (!running && exitCode !== 0) console.log("Could not read config, starting fresh.")
    }

    // Write Config
    Process {
        id: writeProcess
        command: ["sh", "-c", "echo ''"]
        onRunningChanged: if (!running) reloadProcess.running = true
    }

    // Reload Hyprland
    Process {
        id: reloadProcess
        command: ["hyprctl", "reload"]
    }

    Component.onCompleted: {
        readProcess.running = true
    }

    function parseConfig(text) {
        if (!text) {
            keybinds = []
            return
        }
        let binds = []
        let lines = text.split("\n")
        for (let line of lines) {
            line = line.trim()
            if (line.startsWith("bind = ")) {
                let parts = line.substring(7).split(",")
                if (parts.length >= 3) {
                    binds.push({
                        mod: parts[0].trim(),
                        key: parts[1].trim(),
                        dispatcher: parts[2].trim(),
                        params: parts.length > 3 ? parts.slice(3).join(",").trim() : ""
                    })
                }
            }
        }
        keybinds = binds
    }

    function saveConfig() {
        let content = "# Auto-generated by Keybinds Manager\n"
        for (let bind of keybinds) {
            let p = bind.params ? `, ${bind.params}` : ""
            content += `bind = ${bind.mod}, ${bind.key}, ${bind.dispatcher}${p}\n`
        }
        
        try {
            let b64 = btoa(content)
            writeProcess.command = ["sh", "-c", `echo "${b64}" | base64 -d > ${configPath}`]
            writeProcess.running = true
        } catch (e) {
            console.error("Failed to encode config:", e)
        }
    }

    function reloadConfig() {
        // Force re-read the config file to pick up any changes made outside the UI
        readProcess.running = true
        reloadProcess.running = true
    }

    function getKeyString(key) {
        if (key >= Qt.Key_A && key <= Qt.Key_Z) return String.fromCharCode(key).toLowerCase()
        if (key >= Qt.Key_0 && key <= Qt.Key_9) return String.fromCharCode(key)
        if (key === Qt.Key_Return || key === Qt.Key_Enter) return "Return"
        if (key === Qt.Key_Escape) return "Escape"
        if (key === Qt.Key_Tab) return "Tab"
        if (key === Qt.Key_Backspace) return "BackSpace"
        if (key === Qt.Key_Delete) return "Delete"
        if (key === Qt.Key_Space) return "Space"
        if (key === Qt.Key_Left) return "Left"
        if (key === Qt.Key_Right) return "Right"
        if (key === Qt.Key_Up) return "Up"
        if (key === Qt.Key_Down) return "Down"
        if (key === Qt.Key_Comma) return "comma"
        if (key === Qt.Key_Period) return "period"
        if (key === Qt.Key_Slash) return "slash"
        if (key === Qt.Key_Minus) return "minus"
        if (key === Qt.Key_Equal) return "equal"
        if (key >= Qt.Key_F1 && key <= Qt.Key_F35) return "F" + (key - Qt.Key_F1 + 1)
        return "Unknown"
    }

    function editBinding(index) {
        let bind = keybinds[index]
        capturedMod = bind.mod
        capturedKey = bind.key
        dispatcherField.text = bind.dispatcher
        paramsField.text = bind.params
        addDialog.editIndex = index
        addDialog.visible = true
    }

    function deleteBinding(index) {
        let binds = [...keybinds]
        binds.splice(index, 1)
        keybinds = binds
        saveConfig()
        reloadConfig()
    }

    function saveBinding() {
        if (capturedMod === "" || capturedKey === "Unknown") {
            return
        }
        
        let newBind = {
            mod: capturedMod,
            key: capturedKey,
            dispatcher: dispatcherField.text,
            params: paramsField.text
        }
        
        let binds = [...keybinds]
        if (addDialog.editIndex !== -1) {
            binds[addDialog.editIndex] = newBind
        } else {
            binds.push(newBind)
        }
        keybinds = binds
        saveConfig()
        reloadConfig()
        addDialog.visible = false
        addDialog.editIndex = -1
        capturedMod = ""
        capturedKey = ""
    }

    onIsCapturingChanged: {
        if (isCapturing) captureArea.forceActiveFocus()
        else root.forceActiveFocus()
    }

    Keys.onEscapePressed: {
        if (isCapturing) isCapturing = false
        else if (addDialog.visible) addDialog.visible = false
        else root.visible = false
    }

    Rectangle {
        anchors.fill: parent
        color: theme.bg
        opacity: 0.95

        ColumnLayout {
            anchors.fill: parent
            anchors.margins: 24
            spacing: 16

            RowLayout {
                Layout.fillWidth: true
                Label {
                    text: "Hyprland Keybindings"
                    color: theme.text
                    font.family: theme.fontFamily
                    font.pixelSize: 24
                    font.bold: true
                    Layout.fillWidth: true
                }
                Button {
                    text: "+ Add"
                    onClicked: {
                        addDialog.editIndex = -1
                        capturedMod = ""
                        capturedKey = ""
                        dispatcherField.text = "exec"
                        paramsField.text = ""
                        addDialog.visible = true
                    }
                }
                Button {
                    text: "Close"
                    onClicked: root.visible = false
                }
            }

            TextField {
                id: searchField
                Layout.fillWidth: true
                placeholderText: "Search bindings..."
                color: theme.text
                background: Rectangle {
                    color: theme.surface
                    radius: 6
                }
            }

            ListView {
                id: bindList
                Layout.fillWidth: true
                Layout.fillHeight: true
                clip: true
                model: keybinds
                spacing: 8
                
                ScrollBar.vertical: ScrollBar {}

                delegate: Rectangle {
                    width: bindList.width
                    height: visible ? 50 : 0
                    opacity: visible ? 1 : 0
                    Behavior on opacity { NumberAnimation { duration: 150 } }
                    Behavior on height { NumberAnimation { duration: 150 } }
                    color: theme.surface
                    radius: 8
                    
                    property bool matches: searchField.text === "" || 
                                           (modelData.mod + " " + modelData.key + " " + modelData.dispatcher + " " + modelData.params).toLowerCase().indexOf(searchField.text.toLowerCase()) !== -1
                    
                    visible: matches

                    RowLayout {
                        anchors.fill: parent
                        anchors.margins: 12
                        spacing: 16

                        Label {
                            text: `${modelData.mod} + ${modelData.key}`
                            color: theme.accent
                            font.family: theme.fontFamily
                            font.bold: true
                            font.pixelSize: 16
                            Layout.preferredWidth: 180
                        }
                        Label {
                            text: modelData.dispatcher
                            color: theme.text
                            font.family: theme.fontFamily
                            font.weight: Font.DemiBold
                            Layout.preferredWidth: 150
                        }
                        Label {
                            text: modelData.params
                            color: theme.text
                            font.family: theme.fontFamily
                            Layout.fillWidth: true
                            elide: Text.ElideRight
                        }
                        Button {
                            text: "Edit"
                            onClicked: editBinding(index)
                        }
                        Button {
                            text: "Delete"
                            onClicked: deleteBinding(index)
                        }
                    }
                }
            }
        }
    }

    FocusScope {
        id: captureArea
        visible: isCapturing
        focus: visible
        anchors.fill: parent
        z: 999

        Rectangle {
            anchors.fill: parent
            color: "black"
            opacity: 0.7
            MouseArea { anchors.fill: parent }
        }

        ColumnLayout {
            anchors.centerIn: parent
            spacing: 24

            Label {
                text: "Press a key combination..."
                color: "white"
                font.pixelSize: 28
                font.family: theme.fontFamily
                Layout.alignment: Qt.AlignHCenter
            }
            Label {
                text: capturedMod !== "" ? `${capturedMod} + ${capturedKey}` : "..."
                color: theme.accent
                font.pixelSize: 48
                font.family: theme.fontFamily
                font.bold: true
                Layout.alignment: Qt.AlignHCenter
            }
            Button {
                text: "Cancel"
                Layout.alignment: Qt.AlignHCenter
                onClicked: isCapturing = false
            }
        }

        Keys.onPressed: function(event) {
            if (event.key === Qt.Key_Escape) {
                isCapturing = false
                event.accepted = true
                return
            }
            
            if (event.key === Qt.Key_Shift || event.key === Qt.Key_Control || 
                event.key === Qt.Key_Alt || event.key === Qt.Key_Meta ||
                event.key === Qt.Key_AltGr) {
                event.accepted = true
                return
            }

            let mods = []
            if (event.modifiers & Qt.ShiftModifier) mods.push("SHIFT")
            if (event.modifiers & Qt.ControlModifier) mods.push("CTRL")
            if (event.modifiers & Qt.AltModifier) mods.push("ALT")
            if (event.modifiers & Qt.MetaModifier) mods.push("SUPER")

            let keyStr = getKeyString(event.key)
            
            capturedMod = mods.join(" ")
            capturedKey = keyStr
            event.accepted = true
        }
    }

    Rectangle {
        id: addDialog
        visible: false
        anchors.centerIn: parent
        width: 400
        height: 480
        color: theme.bg
        border.color: theme.accent
        border.width: 2
        radius: 12
        z: 1000

        property int editIndex: -1

        ColumnLayout {
            anchors.fill: parent
            anchors.margins: 24
            spacing: 16

            Label {
                text: addDialog.editIndex === -1 ? "Add New Binding" : "Edit Binding"
                font.pixelSize: 20
                font.bold: true
                color: theme.text
                Layout.alignment: Qt.AlignHCenter
            }

            Label { text: "Key Combination"; color: theme.text }
            
            Button {
                Layout.fillWidth: true
                text: isCapturing ? "Capturing..." : (capturedMod !== "" ? `${capturedMod} + ${capturedKey}` : "Click to capture...")
                onClicked: {
                    isCapturing = true
                    capturedMod = ""
                    capturedKey = ""
                }
            }

            Label { text: "Action Type"; color: theme.text }
            ComboBox {
                id: actionCombo
                Layout.fillWidth: true
                model: ["Open App", "Custom Command", "Start Plugin", "Workspace", "Kill Active", "Reload"]
                currentIndex: 0
                color: theme.text
                background: Rectangle {
                    color: theme.surface
                    radius: 6
                }
            }

            Label { text: "Dispatcher"; color: theme.text }
            TextField {
                id: dispatcherField
                Layout.fillWidth: true
                placeholderText: "e.g., exec kitty, exec hyprland, plugin:myplugin"
                color: theme.text
                background: Rectangle {
                    color: theme.surface
                    radius: 6
                }
            }

            Label { text: "Parameters"; color: theme.text }
            TextField {
                id: paramsField
                Layout.fillWidth: true
                placeholderText: "e.g., kitty, 1, plugin:myplugin"
                color: theme.text
                background: Rectangle {
                    color: theme.surface
                    radius: 6
                }
            }

            RowLayout {
                Layout.fillWidth: true
                Layout.topMargin: 16
                Item { Layout.fillWidth: true }
                Button {
                    text: "Cancel"
                    onClicked: addDialog.visible = false
                }
                Button {
                    text: "Save"
                    onClicked: saveBinding()
                }
            }
        }
    }
}